apiVersion: k3d.io/v1alpha3
kind: Simple
name: istio-sandbox
# image: rancher/k3s:v1.22.3-k3s1   # kubeflow install does not worker
image: rancher/k3s:v1.21.7-k3s1     # eventual high cpu load issue, drains battery
# image: rancher/k3s:v1.20.14-k3s1  # high cpu load drains battery
servers: 1
agents: 1
# expose k3d loadbalancer to outside of k3d container
ports:
  - port: 8081:80
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
