apiVersion: k3d.io/v1alpha3
kind: Simple
name: kubeflow
# image: rancher/k3s:v1.22.3-k3s1
servers: 1
agents: 1
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
